[build]
builder = "nixpacks"

[deploy]
startCommand = "bash deploy.sh && php artisan serve --host=0.0.0.0 --port=${PORT}"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[build.args]
PHP_VERSION = "8.2"
NODE_OPTIONS = "--max_old_space_size=2048"
NODE_VERSION = "18"

[build.environment]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"
NPM_CONFIG_PRODUCTION = "false"
APP_KEY = "base64:${APP_KEY:-$(openssl rand -base64 32)}"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
LOG_CHANNEL = "stderr"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"
SESSION_SECURE_COOKIE = "true"

# Database configuration
DB_CONNECTION = "pgsql"
DB_HOST = "${DATABASE_URL}"
DB_PORT = "5432"
DB_DATABASE = "${PGDATABASE}"
DB_USERNAME = "${PGUSER}"
DB_PASSWORD = "${PGPASSWORD}"
DB_CONNECTION = "pgsql"
DB_HOST = "${DATABASE_URL}"
DB_PORT = "${DATABASE_PORT}"
DB_DATABASE = "${DATABASE}"
DB_USERNAME = "${DATABASE_USERNAME}"
DB_PASSWORD = "${DATABASE_PASSWORD}"

# Session configuration
SESSION_DRIVER = "database"
SESSION_LIFETIME = "120"
SESSION_ENCRYPT = "false"

# Cache configuration
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"

# Set application URL
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"

# Set storage link
FILESYSTEM_DISK = "public"

[build.install]
commands = [
  "apt-get update && apt-get install -y libpng-dev libonig-dev libxml2-dev libzip-dev libpq-dev",
  "docker-php-ext-install pdo pdo_mysql pdo_pgsql mbstring exif pcntl bcmath gd zip",
  "chmod +x deploy.sh"
]

[build.build]
commands = [
  # Install PHP dependencies
  "composer install --no-interaction --optimize-autoloader --no-dev",
  
  # Install Node.js dependencies
  "npm ci",
  
  # Build assets
  "npm run build:prod",
  
  # Generate application key if not exists
  "[ -z \"$APP_KEY\" ] && php artisan key:generate --force || echo \"APP_KEY already set\"",
  
  # Cache configuration
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  
  # Set permissions
  "chmod -R 775 storage bootstrap/cache",
  "chmod -R 775 public/build",
  
  # Create storage link
  "php artisan storage:link"
]

[build.start]
commands = ["php-fpm"]

[healthcheck]
enabled = true
path = "/"
initialDelay = 30
timeoutSeconds = 10
intervalSeconds = 15
failureThreshold = 3
