[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"

[build.environment]
NODE_VERSION = "18"

[build.install]
  - "apt-get update && apt-get install -y libpng-dev libonig-dev libxml2-dev"
  - "docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd"

[build.build]
  # Install PHP dependencies
  - "composer install --no-interaction --optimize-autoloader --no-dev"
  
  # Install Node.js dependencies
  - "npm ci"
  
  # Build assets
  - "npm run build"
  
  # Generate application key
  - "php artisan key:generate --force"
  
  # Create storage link
  - "php artisan storage:link"
  
  # Cache configuration
  - "php artisan config:cache"
  - "php artisan route:cache"
  - "php artisan view:cache"
  
  # Set permissions
  - "chmod -R 775 storage bootstrap/cache"
  - "chmod -R 775 public/build"

[build.start]
  - "php-fpm"
