[build]
  builder = "nixpacks"
  buildCommand = "composer install --optimize-autoloader --no-dev && npm install && npm run build"
  startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"
  nixpacks = { version = "v0.11.0" }

[deploy]
  autoRollback = true
  autoMigrate = true
  healthcheckPath = "/health"
  healthcheckTimeout = 60

[env]
  NODE_VERSION = "20.x"
  PHP_VERSION = "8.2"
  COMPOSER_VERSION = "2.7.6"
  NPM_CONFIG_PRODUCTION = "false"
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_LEVEL = "error"
  SESSION_DRIVER = "database"
  SESSION_SECURE_COOKIE = "true"
  SANCTUM_STATEFUL_DOMAINS = "${APP_URL}"
  SESSION_DOMAIN = "${APP_URL}"
  FORCE_HTTPS = "true"
