[build]
builder = "nixpacks"

[deploy]
startCommand = "bash deploy.sh && php artisan serve --host=0.0.0.0 --port=${PORT}"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[build.args]
PHP_VERSION = "8.2"
NODE_OPTIONS = "--max_old_space_size=2048"
NODE_VERSION = "18"

[build.environment]
# Application Settings
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
APP_KEY = "base64:${APP_KEY:-$(openssl rand -base64 32)}"

# Logging
LOG_CHANNEL = "stderr"
LOG_LEVEL = "error"

# Database Configuration
DB_CONNECTION = "pgsql"
DB_HOST = "${DATABASE_URL}"
DB_PORT = "${DATABASE_PORT:-5432}"
DB_DATABASE = "${PGDATABASE:-${DATABASE}}"
DB_USERNAME = "${PGUSER:-${DATABASE_USERNAME}}"
DB_PASSWORD = "${PGPASSWORD:-${DATABASE_PASSWORD}}"

# Session Configuration
SESSION_DRIVER = "database"
SESSION_LIFETIME = "120"
SESSION_SECURE_COOKIE = "true"
SESSION_ENCRYPT = "true"

# Cache & Queue Configuration
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"

# File Storage
FILESYSTEM_DISK = "public"

# Node.js
NPM_CONFIG_PRODUCTION = "false"

[build.install]
commands = [
  # Install system dependencies
  "apt-get update && apt-get install -y libpng-dev libonig-dev libxml2-dev libzip-dev libpq-dev",
  "docker-php-ext-install pdo pdo_mysql pdo_pgsql mbstring exif pcntl bcmath gd zip",
  "chmod +x deploy.sh"
]

[build.build]
commands = [
  # Install PHP dependencies
  "composer install --no-interaction --optimize-autoloader --no-dev",
  
  # Install Node.js dependencies
  "npm ci --no-audit --prefer-offline",
  
  # Build assets for production
  "npm run build",
  
  # Generate application key if not exists
  "[ -z \"$APP_KEY\" ] && php artisan key:generate --force || echo \"APP_KEY already set\"",
  
  # Cache configuration
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  
  # Set permissions
  "chmod -R 775 storage bootstrap/cache",
  "chmod -R 775 public/build",
  
  # Create storage link
  "php artisan storage:link"
]

[build.start]
commands = ["php-fpm"]

[healthcheck]
enabled = true
path = "/"
initialDelay = 30
timeoutSeconds = 10
intervalSeconds = 15
failureThreshold = 3
